### ISSUE TITLE
Fix layout bugs

### ISSUE THREAD

**Issue by Oj18** [oojmed/TTSLO-Web#4]
Firefox (maybe others?):
- Dropdown text has right offset than title ![Screenshot](https://imgur.com/dfTHoRC.png)

All:
- Status text is too far down ![Screenshot](https://imgur.com/TPtPVtR.png) ![Screenshot](https://imgur.com/cuNeTR8.png)

**Comment by RamanaVem** [comment]
Hey @Oj18 can i take a look on this?

**Comment by Oj18** [comment]
@RamanaVem Sorry, someone's already solving it with a pull, #6.

**Comment by RamanaVem** [comment]
Ok cool that's great contribution :)

**Comment by Oj18** [comment]
I'll assign them to not confuse people in the future. :)

**Comment by Oj18** [comment]
Solved via #6.
