### ISSUE TITLE
Make it a Progressive Web App

### ISSUE THREAD

**Issue by Oj18** [oojmed/TTSLO-Web#5]
Things needing to be done (from Lighthouse):
![Screenshot](https://imgur.com/EExe4GF.png)
![Screenshot](https://imgur.com/ZSBtEfA.png)
![Screenshot](https://imgur.com/u349eT0.png)

**Comment by visvxplore** [comment]
I will do it

**Comment by Oj18** [comment]
Sure, thanks a lot @visvxplore.

**Comment by Oj18** [comment]
@visvxplore, @airqz has just made a pull request doing this (#9). Are you okay if I merge their work instead and close this?

**Comment by visvxplore** [comment]
@Oj18, Made a PR, just because I worked on this and for participation in hacktoberfest. I am fine with what ever you can merge, change or adjust the way that suits the project. I implemented just a basic one by going through a tutorial.
